---
name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Install EBPF Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq gcc clang libc6-dev-i386 libbpfcc-dev libbpf-dev linux-tools-common

      - name:  Compile Object file from Source
        run: |
          clang -O2 -Wall -Wextra -target bpf -c -o geneve.o src/geneve.c

      - name: Tar Object File
        run: tar -zcvf geneve.tar.gz geneve.o

      - name: Upload a built artifact for testing
        if: startsWith(github.ref, 'refs/heads/main') == false
        uses: actions/upload-artifact@v3.1.0
        with:
          name: geneve
          path: geneve.tar.gz
