---
name: release

on: 
  merge:
    branches:
      - release-v*

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Install EBPF Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc clang libc6-dev-i386 libbpfcc-dev libbpf-dev linux-tools-common

      - name:  Compile Object file from Source
        run: |
          clang -O2 -Wall -Wextra -target bpf -c -o geneve.o src/geneve.c

      - name: Tar Object File
        run: tar -zcvf geneve.tar.gz geneve.o

      - name: Get the version if release branch
        run: echo "TAG=`echo ${GITHUB_REF#refs/*/} | awk  -F '-' '{print $2}'`" >> $GITHUB_ENV
        env:
          version:  

      - name: Print TAG to check release
        run: |
          echo $TAG
          echo ${{ env.TAG }}

      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload a built artifact for release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: geneve.tar.gz
          asset_name: geneve.tar.gz
          asset_content_type: application/gzip

